### ISSUE TITLE
Got "java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Ljava.net.URL;" When Startup

### ISSUE THREAD

**Issue by MonikaCODE** [MatrixDevTeam/LavaBukkit#41]
Got "java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Ljava.net.URL;" When Startup.

### Server Log:
> [delta@timecity delta]$ sh run.sh
log4j2_server.xml
I was called, when I shouldn't have been!
[17:47:01] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
[17:47:01] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
[17:47:01] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLServerTweaker
[17:47:01] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2768 for Minecraft 1.12.2 loading
[17:47:01] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_201, running on Linux:amd64:3.10.0-862.el7.x86_64, installed at /data/java/jre1.8.0_201
[17:47:01] [main/ERROR] [FML]: Apache Maven library folder was not in the format expected. Using default libraries directory.
[17:47:01] [main/ERROR] [FML]: Full: /data/mc/delta/lavabukkit-1.12.2-R0.1-SNAPSHOT.jar
[17:47:01] [main/ERROR] [FML]: Trimmed: /data/mc/
[17:47:01] [main/INFO] [FML]: Managed to load a deobfuscated Minecraft name- we are in a deobfuscated environment. Skipping runtime deobfuscation
[17:47:01] [main/INFO] [FML]: Ignoring missing certificate for coremod FMLCorePlugin (net.minecraftforge.fml.relauncher.FMLCorePlugin), we are in deobf and it's a forge core plugin
[17:47:01] [main/INFO] [FML]: Ignoring missing certificate for coremod FMLForgePlugin (net.minecraftforge.classloading.FMLForgePlugin), we are in deobf and it's a forge core plugin
[17:47:01] [main/INFO] [FML]: Ignoring missing certificate for coremod LavaInjector (co.matrixdevelopment.lava.asm.LavaInjector), we are in deobf and it's a forge core plugin
[17:47:01] [main/INFO] [FML]: Searching /data/mc/delta/./mods for mods
[17:47:01] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[17:47:01] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[17:47:01] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[17:47:01] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[17:47:01] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:47:02] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:47:02] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:47:02] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[17:47:02] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[17:47:02] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[17:47:02] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.server.MinecraftServer}
[17:47:02] [main/INFO] [STDERR]: [org.bukkit.craftbukkit.Main:main:187]: *** Error, this build is outdated ***
[17:47:02] [main/INFO] [STDERR]: [org.bukkit.craftbukkit.Main:main:188]: *** Please download a new build as per instructions from https://www.spigotmc.org/ ***
[17:47:02] [main/INFO] [STDERR]: [org.bukkit.craftbukkit.Main:main:189]: *** Server will start in 15 seconds ***
[17:47:17] [main/INFO] [STDOUT]: [org.bukkit.craftbukkit.Main:main:194]: Loading libraries, please wait...
[17:47:19] [Server thread/INFO] [minecraft/DedicatedServer]: Starting minecraft server version 1.12.2
[17:47:19] [Server thread/INFO] [FML]: MinecraftForge v14.23.5.2768 Initialized
[17:47:19] [Server thread/INFO] [FML]: Starts to replace vanilla recipe ingredients with ore ingredients.
[17:47:19] [Server thread/INFO] [FML]: Replaced 1036 ore ingredients
[17:47:19] [Server thread/INFO] [FML]: Searching /data/mc/delta/./mods for mods
[17:47:24] [Server thread/INFO] [FML]: Forge Mod Loader has identified 4 mods to load
[17:47:24] [Server thread/WARN] [FML]: Missing English translation for FML: assets/fml/lang/en_us.lang
[17:47:24] [Server thread/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge] at CLIENT
[17:47:24] [Server thread/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge] at SERVER
[17:47:24] [Server thread/INFO] [FML]: Processing ObjectHolder annotations
[17:47:24] [Server thread/INFO] [FML]: Found 1168 ObjectHolder annotations
[17:47:24] [Server thread/INFO] [FML]: Identifying ItemStackHolder annotations
[17:47:24] [Server thread/INFO] [FML]: Found 0 ItemStackHolder annotations
[17:47:24] [Server thread/INFO] [FML]: Configured a dormant chunk cache size of 0
[17:47:24] [Forge Version Check/INFO] [forge.VersionCheck]: [forge] Starting version check at http://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[17:47:24] [Server thread/INFO] [FML]: Applying holder lookups
[17:47:24] [Server thread/INFO] [FML]: Holder lookups applied
[17:47:24] [Server thread/INFO] [FML]: Applying holder lookups
[17:47:24] [Server thread/INFO] [FML]: Holder lookups applied
[17:47:24] [Server thread/INFO] [FML]: Applying holder lookups
[17:47:24] [Server thread/INFO] [FML]: Holder lookups applied
[17:47:24] [Server thread/INFO] [FML]: Applying holder lookups
[17:47:24] [Server thread/INFO] [FML]: Holder lookups applied
[17:47:24] [Server thread/INFO] [FML]: Injecting itemstacks
[17:47:24] [Server thread/INFO] [FML]: Itemstack injection complete
[17:47:24] [Server thread/INFO] [minecraft/DedicatedServer]: Loading properties
[17:47:24] [Server thread/INFO] [minecraft/DedicatedServer]: Default game type: SURVIVAL
[17:47:24] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Ljava.net.URL;
        at co.matrixdevelopment.lava.pluginmanager.LavaPluginManager.<init>(LavaPluginManager.java:21) ~[lavabukkit-1.12.2-R0.1-SNAPSHOT.jar:git-LavaBukkit-048b6bf]
        at org.bukkit.craftbukkit.CraftServer.<init>(CraftServer.java:222) ~[lavabukkit-1.12.2-R0.1-SNAPSHOT.jar:git-LavaBukkit-048b6bf]
        at net.minecraft.server.management.PlayerList.<init>(PlayerList.java:123) ~[lavabukkit-1.12.2-R0.1-SNAPSHOT.jar:git-LavaBukkit-048b6bf]
        at net.minecraft.server.dedicated.DedicatedPlayerList.<init>(DedicatedPlayerList.java:18) ~[lavabukkit-1.12.2-R0.1-SNAPSHOT.jar:git-LavaBukkit-048b6bf]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:231) ~[lavabukkit-1.12.2-R0.1-SNAPSHOT.jar:git-LavaBukkit-048b6bf]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:654) [lavabukkit-1.12.2-R0.1-SNAPSHOT.jar:git-LavaBukkit-048b6bf]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
[17:47:24] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: /data/mc/delta/./crash-reports/crash-2019-02-06_17.47.24-server.txt
[17:47:24] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
[17:47:24] [Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds
[17:47:24] [Server thread/INFO] [FML]: The state engine was in incorrect state POSTINITIALIZATION and forced into state SERVER_STOPPED. Errors may have been discarded.
[delta@timecity delta]$ 
### Crash-Report:
---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 19-2-6 PM5:47
Description: Exception in server tick loop

java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Ljava.net.URL;
	at co.matrixdevelopment.lava.pluginmanager.LavaPluginManager.<init>(LavaPluginManager.java:21)
	at org.bukkit.craftbukkit.CraftServer.<init>(CraftServer.java:222)
	at net.minecraft.server.management.PlayerList.<init>(PlayerList.java:123)
	at net.minecraft.server.dedicated.DedicatedPlayerList.<init>(DedicatedPlayerList.java:18)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:231)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:654)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 3.10.0-862.el7.x86_64
	Java Version: 1.8.0_201, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 222153440 bytes (211 MB) / 630194176 bytes (601 MB) up to 3702521856 bytes (3531 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	CraftBukkit Information: 
   Running: 
   Failed to handle CraftCrashReport:
java.lang.NullPointerException
	at org.bukkit.Bukkit.getName(Bukkit.java:92)
	at org.bukkit.craftbukkit.CraftCrashReport.call(CraftCrashReport.java:20)
	at net.minecraft.crash.CrashReportCategory.func_189529_a(CrashReportCategory.java:96)
	at net.minecraft.crash.CrashReport.func_71504_g(CrashReport.java:120)
	at net.minecraft.crash.CrashReport.<init>(CrashReport.java:41)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:713)
	at java.lang.Thread.run(Thread.java:748)

	FML: MCP 9.42 Powered by Forge 14.23.5.2768 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID        | Version      | Source                              | Signature |
	|:----- |:--------- |:------------ |:----------------------------------- |:--------- |
	| UCH   | minecraft | 1.12.2       | minecraft.jar                       | None      |
	| UCH   | mcp       | 9.42         | minecraft.jar                       | None      |
	| UCH   | FML       | 8.0.99.99    | lavabukkit-1.12.2-R0.1-SNAPSHOT.jar | None      |
	| UCH   | forge     | 14.23.5.2768 | lavabukkit-1.12.2-R0.1-SNAPSHOT.jar | None      |

	Loaded coremods (and transformers): 
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by GMatrixGames** [comment]
This issue was already reported on Discord, but thank you for letting us know as well.

@ca1halman should be fixing it today, so look out for an update in Discord.
